### PR TITLE
update for updated ldats

### PR DESCRIPTION
**Pull request by juniperlsimonis**
ldats code and function names have been updated, pulling those updates through here to the drake pipeline

should address #36 
@ethanwhite can you verify that this branch's code will work for you?

### CODE REVIEW

**Comment by ethanwhite** [comment]
It fixed the initial error, but now I have:

```
ethan@oneesk:~/Dropbox/Research/MATSS/MATSS-pipeline/analysis (master)$ Rscript pipeline.R 
...
target lda_portal_data
load 1 item: portal_data
fail lda_portal_data
Error: Target `lda_portal_data` failed. Call `diagnose(lda_portal_data)` for details. Error message:
  unused argument (ncores = 2)
Execution halted
```

**Comment by juniperlsimonis** [comment]
huh. I don't quite get what's going on here, but I can semi-recreate the issue you got. What seems to resolve it is making sure that the "Analysis methods" code is
```
methods <- drake_plan(
    lda = run_LDA(dataset__, max_topics = 6, nseeds = 20)
)
```
It should be this already (as it is on line 28 here /analysis/pipeline.R) , but for some reason that change didn't get pulled down to the local copy I have of the repo. When I edited it to remove the `ncores = 2` argument that was there it ran fine, but then github showed no change in the code itself, so I'm quite baffled. 

So @ethanwhite what is on that line in your local version of the /analysis/pipeline.R script? If it has the `ncores = 2` argument, can you delete that and re-run the pipeline to see if it works? And if so, what happens when you try to commit just that singular change in the script?

**Comment by ethanwhite** [comment]
Ooops. Totally my fault. Sorry. I installed the branch, so I got the updated core MATSS-pipeline code, but I didn't checkout the branch, so I was using the old `pipeline.R`. Everything is working fine for me now.

**Comment by juniperlsimonis** [comment]
ah! word, thanks for the update! ok @ha0ye let me know when you've had a chance to look this over

**Review by ha0ye — COMMENTED** [review]
Is there a reason to use `.drake/.gitignore` instead of adding `.drake` to the top-level `.gitignore`?

**Comment by juniperlsimonis** [comment]
honestly, I'm not sure/don't recall, but I think that file autopopulated? i'm still really green with the whole drake thing, so i don't know if i set that up right or not?

for reference, in my local version, the `.drake` folder has folders named `config`, `data`, `keys`, and `scratch`, and so the way that `.gitignore` file works, it basically ignores everything within the `.drake` folder except itself.

**Comment by juniperlsimonis** [comment]
ostensibly, i think if we wanted to move the contents of the `.drake/.gitignore` upwards to the main `.gitignore`, we'd want to write it as
```
.drake/*
!.drake/.gitignore
```
right?

**Comment by ha0ye** [comment]
I think the only reason for the `!/.gitignore` currently is so that `.drake/.gitignore` is able to be tracked.  If we're using `/.gitignore`, then that's not an issue so I think we only need to add `/.drake/` to the root-level .gitignore.

**Comment by juniperlsimonis** [comment]
ohh gotcha. should it be `/.drake/` or `.drake/`?

**Comment by ha0ye** [comment]
I was wondering that myself and settled on `/.drake/` so that it only excludes the .drake folder if it's in root, as opposed to if it were nested in some other folder. (seems unlikely, but still)

**Comment by juniperlsimonis** [comment]
updated

**Pull request merged**
