### PR TITLE
basic time series summary statistics functions [WIP]

### PR DESCRIPTION
**Pull request by juniperlsimonis**
including multivariate and univariate version based on numeric time or date, with flexible support for effort correction and interpolation of missing values for autocorrelation
as of now, just includes the functions, which work on the portal rodents. doesn't yet include the `.Rmd` to collate results or the integration into the pipeline

### CODE REVIEW

**Comment by juniperlsimonis** [comment]
ok, so the summary stats functionality is now generalized to work on all four of the datasets in the version i'm working with (portal, maizuru, jornada, sgs). i've also shifted around some of the data preparation code, but the pipeline still works well with just those changes.

**note** I've also updated the portal data to be on new moons rather than periods, so that we have recognition of the uneven spacing, which is needed for the time series modeling

however, when i try to integrate the summary function into the pipeline in the definition of `methods` (in "## Analysis Methods"), it errors in the markdown rendering stage, and it looks like the lda report is thinking the results from the summary function are lda output. 

Clearly then, I don't quite understand how exactly to slot the summary function into the workflow as it is, but the function works, and it would be great for everyone else working on this to see/be able to work with the updated data structure (with the metadata element added to the list), yeah? Given that, what do you think about merging this in now, @ha0ye ?

**Comment by ha0ye** [comment]
So I think the issue is that the `lda_results_plan` ends up including the summary outputs. It looks like the way to separate it might be to use `gather_by()` instead of `gather_plan()`, but those functions, along with `plan_analyses` are getting deprecated, so....

We'll want to rewrite some stuff using `map_plan()`? Give me a bit of time to work out the kinks in master and work this in, so that you can rebase, etc.
https://ropenscilabs.github.io/drake-manual/plans.html#large-plans

**Comment by ha0ye** [comment]
> map_plan()

Oops, misspoke, `map_plan()` is also deprecated. Regardless, I have a new implementation using the [transformations approach](https://ropenscilabs.github.io/drake-manual/plans.html#large-plans).

I should have an update to master branch in a bit, after checking that the current build works.

**Comment by ha0ye** [comment]
Ok, @juniperlsimonis, you should be able to add a new summary method now, and not bungle `lda_report.Rmd`.

Do watch out for the changes in `lda_report.Rmd`, which need to mirror the code in `pipeline.R` to find the correct cache.

And check the targets in the `pipeline` data.frame to see what name is given to the list of summary outputs.

**Comment by juniperlsimonis** [comment]
@ha0ye I'm having difficult with running the analysis pipeline script.
i'm getting an error when i try to run the pipeline, whether it's on this branch with a current-to-here version of the package installed or on the master branch with a current-to-there version of the package installed:
image

**Comment by ha0ye** [comment]
Can you check your version of Drake and update if necessary? Some of the code for setting up the plan is in a *very* new version (6.2.1, I think)

**Comment by juniperlsimonis** [comment]
drake_6.2.1.9003

**Comment by ha0ye** [comment]
Weird, maybe the parallelization conflicts with Windows?

**Comment by ha0ye** [comment]
I think it might be doing mclapply under the hood. Is that one of the ones that doesn't work?

**Comment by juniperlsimonis** [comment]
how do i tell what isn't working?

**Comment by ha0ye** [comment]
It *looks* like a parallelization error, and it sounds like `future::multiprocess` will do different things on windows : https://www.rdocumentation.org/packages/future/versions/1.10.0/topics/multiprocess

I'm seeing if I can reproduce it now by using future::multisession, which may run into issues with Drake??

**Comment by ha0ye** [comment]
Ok, I'm just having a lot of issues in general with Drake caching and parallelization (it's being really wonky with targets failing, and somehow invalidating dependencies in the process). I'm starting to lean towards not trying to use SQLite for the underlying cache.

**Pull request merged**
