### PR TITLE
Make data storage path into a variable that can be changed by the user.

### PR DESCRIPTION
**Pull request by diazrenata**
We may not continue to store data within the repo (?). But, as long as we do, it's helpful to be able to specify where the `data` folder is. 

This is one way to do it. Specify the data directory location at the top of the pipeline, so it is in the environment when the pipeline runs `plan_datasets`. 

I think it would be cleaner to be able to pass `folder_path` as an argument? But I did not succeed in doing that, so this was the faster workaround. 🤷‍♀️

### CODE REVIEW

**Comment by ha0ye** [comment]
I think this might do some weird things, because calling the function to make the plan might do funny things based on whether or not `folder_path` is specified in the calling environment?

I'm going to go ahead and work on this problem in https://github.com/weecology/portalr/issues/185, as a solution there can get brought into here through `portalr` as a dependency of `MATSS`.

**Comment by diazrenata** [comment]
That’s exactly how it works :p. I got tangled up trying to get it to move
around as argument and gave up........so if there is a better way that is v
good news!

**Comment by ha0ye** [comment]
Ahhhh, yeah, I bet if you tried to pass `folder_path` in as an argument to the function, you'd need `!!` or some other NSE syntax to get it to work. :half_scream_cat:

**Comment by ha0ye** [comment]
@diazrenata I think this is resolved, but if you want to make changes to the default # of topics and seeds for the LDA function to speed things up, feel free to do so directly. I think we can close this PR afterward.

**Comment by diazrenata** [comment]
I think we can close it right now. It’s pretty easy to make the changes to
the LDA, and I was going to migrate the actual call to run_LDA to
MATSS-LDATS soon anyway.

(Thanks for solving this, also! It had become a struggle :P)

**Pull request closed without merging**
