### PR TITLE
Import BBS data by route

### PR DESCRIPTION
**Pull request by diazrenata**
Functions to 

- subset the BBS data to sufficiently long timeseries
- extract each route and clean species labels, etc
- add the community data for every route to `datasets` plans

The initial processing step (`prepare_bbs_ts_data`) does the cleaning and subsetting necessary to get the list of routes and regions for the plans, and saves the processed abundance table and the tables for making the plans in the directory with the `data` path.  The remaining functions load those data tables as needed (trying to minimize the number of times we interact with the main dataframe - it's slow to load). 

`get_bbs_route_region_data` pulls a specified route + region and does the final cleaning on it. I've broken the cleaning into two steps because this last step takes forever and crashed R for me a few times when I tried to do it on the whole dataframe at once. 

`build_bbs_datasets_plan` makes a drake plan to get data for all the routes.  (2500 of them)

`build_datasets_plan` now includes the option to include BBS, in which case it will use `build_bbs_datasets_plan`. 

handles #125

### CODE REVIEW

**Review by ha0ye — CHANGES_REQUESTED** [review]
Some general notes:
* `build_datasets_plan()`, `build_bbs_datasets_plan()`, `prepare_bbs_ts_data()`, and `get_bbs_route_region_data()` all take a path argument, but the path argument isn't consistently passed between them, and so the default option is relied on.
* some of the file paths are created using paste0; I think the recommend approach is to use `file.path()` so that we don't run into issues with forward-slash, back-slash confusion (across different operating systems)
* one line 130, the call to `get_bbs_route_region_data()` doesn't use the path argument, and it probably needs `!!`, as on lines 93 and 94.
* should the default `end_yr` in `prepare_bbs_ts_data()` be 2017? Maybe we can add the option to have the argument be NA, and have it be ignored?

**Comment by ha0ye** [comment]
More generally, it seems like `get_bbs_route_region_data()` is pretty slow, and I think this is because it's trying to load the entire bbs dataset. Since it seems like the new workflow is for `prepare_bbs_ts_data()` to be called first, maybe it should split the data into separate files for each route x region, which then speeds up `get_bbs_route_region_data()`?

**Comment by diazrenata** [comment]
@ha0ye, could you maybe take a look at this version of things? Hopefully it's a little more streamlined!

**Comment by ha0ye** [comment]
@diazrenata I just noticed that you have files in `vignettes/.drake` as part of your commit - did you mean to include those?

**Comment by diazrenata** [comment]
:eyes: Nope -apologies! I can get rid of them and fix the gitignore in a
few...

**Review by ha0ye — APPROVED** [review]

**Pull request merged**
