### PR TITLE
Summarize bbs regions by year

### PR DESCRIPTION
**Pull request by gmyenni**
Use `bcr` the 'bird conservation region' to group routes.
Summarize by year

### CODE REVIEW

**Review by ha0ye — COMMENTED** [review]
I think @diazrenata is focusing on trying to get the BBS data in order for analysis, and may be checking against BBS pre-processing from elsewhere, but I have a few quick notes:
* why is the default end_yr = 2017? Is this because of the delay in getting newer BBS data processed and/or getting it into retriever?

**Comment by gmyenni** [comment]
> * why is the default end_yr = 2017? Is this because of the delay in getting newer BBS data processed and/or getting it into retriever?

No, it doesn't really need to be. There isn't 2018 data yet, but it won't fail even if end_yr = 2019.

**Comment by diazrenata** [comment]
I've been looking into using scripts from https://github.com/weecology/bbs-forecasting/blob/master/R/forecast-bbs-core.R as a starting point for BBS data. I'm pretty new to BBS, so, my thoughts come with that qualification.

There are a couple of points of difference that might or might not be important(?) -
* Summarizing by "conservation region" vs. route. Do we consider routes analogous to plots, and conservation regions the right scale for a "community"? Naively I would have guessed that routes are more community-scale? Happy to investigate this more but I'm sure @gmyenni, @ethanwhite have a better sense of this atm. 
* The scripts in the forecasting repo have some cleaning steps that, naively, seem like a good idea. (Removing poorly-sampled species, combining subspecies into the common species, etc). Any objection to porting those over?

**Comment by ethanwhite** [comment]
I think it's a great idea to start with those functions. 

> Summarizing by "conservation region" vs. route. Do we consider routes analogous to plots, and conservation regions the right scale for a "community"? Naively I would have guessed that routes are more community-scale?

You're right. Routes are typically considered community scale. BCR is closer to biome. 

> The scripts in the forecasting repo have some cleaning steps that, naively, seem like a good idea. (Removing poorly-sampled species, combining subspecies into the common species, etc). Any objection to porting those over?

Those are fairly standard steps with BBS data (we've used them in everything BBS for over a decade) so I'm definitely :+1: on including them.

**Comment by diazrenata** [comment]
#124 I added the cleaning functions from bbs-forecasting and added an argument to subset by route. 

I added the region & route information as columns in `covariates`. 

(I think the next step is to do some kind of wrapper to run All the Data for All the Routes through.)

**Comment by gmyenni** [comment]
Yeah, I started from https://github.com/weecology/bbs-forecasting. I just removed the stuff that I thought LDATS doesn't do. But @diazrenata obviously you know how LDATS works better than I, so I can leave this to you from now on.

I thought we would want to reduce the number of BBS communities in the data, by treating routes as subsamples within a larger region. But LDATS can't handle multiple time series within a dataset, right? So if that functionality isn't going to be added any time soon, we can just leave it at the route level and not worry about it.

**Comment by diazrenata** [comment]
Thanks! I agree, for now at least, route level is the way to go. I don't think `LDATS` can use the grouping-by-region information yet.

**Pull request closed without merging**
