### PR TITLE
By route and cleaning

### PR DESCRIPTION
**Pull request by diazrenata**
Summarize at route level and clean using functions from weecology/bbs-forecasting.

### CODE REVIEW

**Review by gmyenni — APPROVED** [review]
I only had time to skim this before leaving town, but LGTM!!

**Comment by diazrenata** [comment]
#125 I made an initial attempt at handling all the BBS data at once. It appears to work (... :crystal_ball:) but it might be buggy and it might break some dependencies.

**Comment by ha0ye** [comment]
@diazrenata Do you want me to take a look at anything here, or should I hold off for now?

**Comment by diazrenata** [comment]
#127 is the one to look at now! And (good timing!), I think it is to a point where it would be helpful if you get a chance to look at it. 🎉

**Pull request closed without merging**
